#!/usr/bin/env bun
/**
 * `bun run clean:generated` — remove all gitignored generated artifacts
 * (build output, codegen, caches, coverage, test reports) while preserving
 * local secrets and setup state.
 *
 * Backed by `git clean -dXff` so removal is driven entirely by `.gitignore`
 * (recursive across workspaces, never touches committed files like
 * `.agents/skills/pr-push`). Restorable artifacts are regenerated by
 * `bun run setup` (skills) and `bun run codegen` (Convex types).
 *
 * Protected from removal:
 *   - `.env.local` and nested copies (local secrets)
 *   - `.svelter/` (local setup state — `setup.json`, env zone files)
 *   - `.husky/_/` (regenerated by `prepare`, but cheap to keep)
 *
 * @example
 *   bun run clean:generated
 *   bun run clean:generated --dry-run
 */
import { spawnSync } from "node:child_process";
import { cpSync, existsSync, mkdtempSync, readdirSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";

const dryRun =
  process.argv.includes("--dry-run") || process.argv.includes("-n");

/** Paths to protect from `git clean -dXff` (relative to repo root). */
const PROTECTED = [
  ".env.local",
  ".env.*.local",
  "apps/web/.env.local",
  "convex/.env.local",
  ".svelter",
  ".husky/_",
];

const root = resolve(import.meta.dirname, "..", "..");

/**
 * Snapshot protected paths that exist into a temp dir, returning the temp
 * dir path (or null if nothing needed protecting).
 */
function snapshot(): string | null {
  const existing = PROTECTED.filter((p) => existsSync(join(root, p)));
  if (existing.length === 0) return null;
  const tmp = mkdtempSync(join(tmpdir(), "clean-snapshot-"));
  for (const p of existing) {
    cpSync(join(root, p), join(tmp, p), { recursive: true });
  }
  return tmp;
}

/** Restore snapshot from temp dir back into the repo, then remove temp. */
function restore(tmp: string): void {
  for (const entry of readdirSync(tmp)) {
    if (entry === ".DS_Store") continue;
    cpSync(join(tmp, entry), join(root, entry), { recursive: true });
  }
  rmSync(tmp, { recursive: true, force: true });
}

const tmp = dryRun ? null : snapshot();

const args = ["clean", "-dXff"];
if (dryRun) args.push("-n");
spawnSync("git", args, { stdio: "inherit", cwd: root });

if (tmp) restore(tmp);
