import { afterEach, describe, expect, it } from "bun:test";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import {
  clerkBindZonePath,
  legacyClerkBindZonePath,
  parseClerkBindZone,
  relocateClerkBindZoneToSvelter,
} from "./clerk-dns-zone";

const SAMPLE_ZONE = `; Generated by clerk deploy
$ORIGIN extractora.com.
$TTL 300

clerk.extractora.com.	IN	CNAME	frontend-api.clerk.services.
accounts.extractora.com.	IN	CNAME	accounts.clerk.services.
`;

describe("parseClerkBindZone", () => {
  it("parses CNAME rows from a clerk deploy zone export", () => {
    expect(parseClerkBindZone(SAMPLE_ZONE)).toEqual([
      {
        name: "clerk.extractora.com",
        type: "CNAME",
        content: "frontend-api.clerk.services",
      },
      {
        name: "accounts.extractora.com",
        type: "CNAME",
        content: "accounts.clerk.services",
      },
    ]);
  });
});

describe("relocateClerkBindZoneToSvelter", () => {
  let root = "";

  afterEach(() => {
    if (root) {
      rmSync(root, { recursive: true, force: true });
      root = "";
    }
  });

  it("moves a legacy repo-root zone file into .svelter/", () => {
    root = mkdtempSync(join(tmpdir(), "clerk-zone-"));
    const apex = "extractora.com";
    writeFileSync(legacyClerkBindZonePath(root, apex), SAMPLE_ZONE, "utf8");

    const dest = relocateClerkBindZoneToSvelter(root, apex);
    expect(dest).toBe(clerkBindZonePath(root, apex));
    expect(parseClerkBindZone(readFileSync(dest!, "utf8"))).toHaveLength(2);
  });
});
